server:
  port: 0

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  application:
    name: ${NAME}
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER_NAME}
    password: ${RABBITMQ_USER_PASS}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASS}
    url: ${DB_URL}

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER}

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}
    s3:
      bucket: ${AWS_S3_BUCKET}
      post-image-prefix: ${AWS_S3_POST_PREFIX}
      base-url: ${AWS_S3_BASE_URL}
    region:
      static: ${AWS_REGION_STATIC}
    stack:
      auto: false

post:
  pagination:
    default-size: ${POST_PAGINATION_DEFAULT_SIZE}
  title:
    max-length: ${POST_TITLE_MAX_LENGTH}
  contents:
    max-length: ${POST_CONTENTS_MAX_LENGTH}